//! Surface-independent GPU rendering primitives.

pub mod allocation_stats;
pub mod atmosphere;
pub mod chunk_pipeline;
pub mod clouds;
pub mod day_cycle;
pub mod deferred;
pub mod depth_pyramid;
pub mod draw_lists;
pub mod final_pass;
pub mod frame_targets;
pub mod frustum;
pub mod gbuffer;
pub mod gi;
pub mod globals;
pub mod gpu;
pub mod gpu_timing;
pub mod gtao;
pub mod lod_pipeline;
pub mod m7_effects;
pub mod m8_graph;
pub mod materials;
pub mod memory;
pub mod noise;
pub mod offscreen;
pub mod outline;
pub mod pbr;
pub mod post;
pub mod preset;
pub mod renderer;
mod renderer_chunks;
pub mod runtime_effects;
pub mod scene_bindings;
pub mod screenshot;
pub mod shader_source;
pub mod shader_watch;
pub mod shadow;
pub mod temporal;
pub mod textures;
pub mod translucent;
pub mod ui;
pub mod ui_blur;
pub mod volumetric;
pub mod water;
pub mod water_pipeline;

pub use chunk_pipeline::{ChunkPipeline, ChunkSlot, GpuChunk, GpuChunkMeshes};
pub use day_cycle::{DAY_LENGTH_SECONDS, DayState, day_state};
pub use deferred::{DeferredDebug, DeferredPipeline};
pub use frustum::Frustum;
pub use globals::Globals;
pub use gpu::Gpu;
pub use materials::{MaterialArrays, MaterialGpu};
pub use offscreen::{OffscreenTarget, read_pixels};
pub use outline::OutlinePipeline;
pub use preset::RenderPreset;
pub use renderer::{RenderView, Renderer};
pub use scene_bindings::SceneBindings;
pub use shader_watch::ShaderWatcher;
pub use textures::BlockTextures;
pub use translucent::TranslucentPipeline;
